### ISSUE TITLE
download() missing 1 required positional argument: 'progress_callback'

### ISSUE THREAD

**Issue by BobleChinois** [lightning-power-users/node-launcher#322]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [] support request

* **What is the current behavior?**
I want to run current master for some testing on Linux, and followed instructions under the [Development section](https://github.com/lightning-power-users/node-launcher#development) of the README.md file.

When I run `python run.py`, the node-launcher seems to get stuck when it tries to download tor node, bitcoin node and lnd node, it just stay there and didn't move in a few minutes until I killed it.
Here is the complete output:
```
2019-04-25 15:41:57 [debug    ] Registered VCS backend: git
2019-04-25 15:41:57 [debug    ] Registered VCS backend: hg
2019-04-25 15:41:57 [debug    ] Registered VCS backend: svn
2019-04-25 15:41:57 [debug    ] Registered VCS backend: bzr
2019-04-25 15:41:57 [info     ] constants                      NODE_LAUNCHER_RELEASE=6.1.0 OPERATING_SYSTEM=linux TARGET_BITCOIN_RELEASE=v0.17.1 TARGET_LND_RELEASE=v0.6-beta-rc4
Traceback (most recent call last):
  File "/home/sosthene/Github/node-launcher/node_launcher/gui/components/thread_worker.py", line 71, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: check_version() missing 1 required positional argument: 'progress_callback'
2019-04-25 15:41:57 [debug    ] Starting node set
2019-04-25 15:41:57 [debug    ] update_status tor software     new_status=checking_download
2019-04-25 15:41:57 [debug    ] update_status tor node         network=tor new_status=checking_download old_status=None
2019-04-25 15:41:57 [debug    ] update_status tor software     new_status=downloading_software
2019-04-25 15:41:57 [debug    ] update_status tor node         network=tor new_status=downloading_software old_status=checking_download
Traceback (most recent call last):
  File "/home/sosthene/Github/node-launcher/node_launcher/gui/components/thread_worker.py", line 71, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: download() missing 1 required positional argument: 'progress_callback'
2019-04-25 15:41:57 [debug    ] update_status tor software     new_status=software_downloaded
2019-04-25 15:41:57 [debug    ] update_status tor node         network=tor new_status=software_downloaded old_status=downloading_software
2019-04-25 15:41:57 [debug    ] update_status bitcoind software new_status=checking_download
2019-04-25 15:41:57 [debug    ] update_status bitcoin node     network=bitcoin new_status=checking_download old_status=None
2019-04-25 15:41:57 [debug    ] update_status bitcoind software new_status=downloading_software
2019-04-25 15:41:57 [debug    ] update_status bitcoin node     network=bitcoin new_status=downloading_software old_status=checking_download
Traceback (most recent call last):
  File "/home/sosthene/Github/node-launcher/node_launcher/gui/components/thread_worker.py", line 71, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: download() missing 1 required positional argument: 'progress_callback'
2019-04-25 15:41:57 [debug    ] update_status bitcoind software new_status=software_downloaded
2019-04-25 15:41:57 [debug    ] update_status bitcoin node     network=bitcoin new_status=software_downloaded old_status=downloading_software
2019-04-25 15:41:57 [debug    ] update_status lnd software     new_status=checking_download
2019-04-25 15:41:57 [debug    ] update_status lnd node         network=lnd new_status=checking_download old_status=None
2019-04-25 15:41:57 [debug    ] update_status lnd software     new_status=downloading_software
2019-04-25 15:41:57 [debug    ] update_status lnd node         network=lnd new_status=downloading_software old_status=checking_download
Traceback (most recent call last):
  File "/home/sosthene/Github/node-launcher/node_launcher/gui/components/thread_worker.py", line 71, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: download() missing 1 required positional argument: 'progress_callback'
2019-04-25 15:41:57 [debug    ] update_status lnd software     new_status=software_downloaded
2019-04-25 15:41:57 [debug    ] update_status lnd node         network=lnd new_status=software_downloaded old_status=downloading_software
^CTerminated
```

* **If the current behavior is a bug, please provide the steps to reproduce**
Just run exactly the same commands as in the README file.

* **What is the expected behavior?**
Node-launcher should download all that it needs and start-up after a while, I guess.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [Linux ]
Here my Linux version:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"
Kernel: Linux 4.19.32-1-MANJARO

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rthowell** [comment]
Having the same issue running 19.04
![Screenshot from 2019-04-29 00-10-37](https://user-images.githubusercontent.com/47626311/56881515-7c132e00-6a15-11e9-99dd-50fb157554dc.png)

**Comment by PierreRochard** [comment]
Hi @BobleChinois and @rthowell! I just merged in a branch ( https://github.com/lightning-power-users/node-launcher/pull/324 ) which should fix this problem, let me know if it doesn't!

**Comment by BobleChinois** [comment]
Hi @PierreRochard, thanks for the update, unfortunately I still get the exact same error after upgrading to latest commit.
I already had a look but wasn't able to figure it out, I'll try again tomorrow. Looking at the `thread_worker.py` file didn't help much, do you have any tip?

**Comment by rthowell** [comment]
Got the new master with merged branch but still have the same error message. Looks like your update was to tests/test_node_set/test_bitcoind/test_bitcoind_configuration.py. 

The error appears to be thrown in /node-launcher/node_launcher/gui/components/thread_worker.py
